name: build
on:
  push:
    branches: [ main ]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        id: task1
        run: exit 1

      - name: Step 2
        id: task2
        run: exit 0
        if: failure()

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        id: task1
        run: exit 1