name: build
on:
  push:
    branches: [ main ]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'npm'

      - name: test
        uses: nick-fields/retry@v2.4.0
        id: test
        with:
          warning_on_retry: true
          timeout_minutes: 10
          max_attempts: 3
          command: yarn test
          # new_command_on_retry: |
          #   yarn test2
  # job2:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - job1
  #   if: always()
  #   steps:
  #     - run: echo ${{needs.job1.outputs.test_result}}