name: build
on:
  push:
    branches: [ main ]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        id: task1
        run: |
          exit 1

      - name: Step 2
        id: task2
        if: steps.task1.outcome != 'success'
        run: |
          exit 0

  # job2:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - job1
  #   if: ${{ needs.job1.outputs.test-output == 'success' }}
  #   steps:
  #     - name: Step 1
  #       id: task1
  #       run: exit 1