name: build
on:
  push:
    branches: [ main ]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        id: task1
        run: exit 0
        continue-on-error: true

      - name: Step 2
        id: task2
        run: exit 1
        if: failure()
