name: build
on:
  push:
    branches: [ main ]

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      test-output: ${{ steps.task1.outcome || steps.task2.outcome }}
    steps:
      - name: Step 1
        continue-on-error: true
        id: task1
        run: |
          exit 1

      - name: Step 2
        id: task2
        if: failure()
        run: |
          exit 0

  job2:
    runs-on: ubuntu-latest
    needs:
      - job1
    if: ${{ needs.job1.outputs.test-output == 'success' }}
    steps:
      - name: Step 1
        id: task1
        run: exit 1