name: build
on:
  push:
    branches: [ main ]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Step 1
        id: task1
        run: |
          yarn test1

      - name: Step 2
        if: failure()
        id: task2
        run: |
          yarn test2

  # job2:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - job1
  #   if: ${{ needs.job1.outputs.test-output == 'success' }}
  #   steps:
  #     - name: Step 1
  #       id: task1
  #       run: exit 1