name: build
on:
  push:
    branches: [ main ]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Step 1
        id: task1
        run: |
          yarn test2

      - name: Step 2
        uses: nick-fields/retry@v2
        id: task2
        run: |
          yarn test1
        with:
          max_attempts: 3

  # job2:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - job1
  #   if: always()
  #   steps:
  #     - run: echo ${{needs.job1.outputs.test_result}}