name: build
on:
  push:
    branches: [ main ]

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      test_result: ${{ steps.task1.outputs.test_result || steps.task2.outputs.test_result }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Step 1
        id: task1
        run: |
          yarn test1
          echo '::set-output name=test_result::success'
        continue-on-error: true

      - name: Step 2
        id: task2
        if: failure()
        run: |
          yarn test2
          echo '::set-output name=test_result::success'


  job2:
    runs-on: ubuntu-latest
    needs:
      - job1
    steps:
      - run: echo ${{needs.job1.outputs.test_result}}